{% set name = "jupyterlab-spellchecker" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-spellchecker-{{ version }}.tar.gz
  sha256: 581f99e4fd9229f1bd8db6cad25ebb8599d0207177f06b5f1ae095c9394be001

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.6
  run:
    - jupyterlab ~=3.0
    - python >=3.6

test:
  imports:
    - jupyterlab_spellchecker
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "@ijmbarr/jupyterlab_spellchecker.*OK"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/spellchecker
  summary: A spell checker for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
